ALTER TABLE historico ALTER COLUMN his_id SET DEFAULT NEXTVAL('hibernate_sequence'::regclass);

CREATE FUNCTION HISTORICO() RETURNS TRIGGER AS $$
	DECLARE
		 ANTIGO NUMERIC (9,2);
		 NOVO NUMERIC (9,2);
		 ID INT;
	BEGIN
		ANTIGO = OLD.PRO_ENTRADA;
		NOVO = NEW.PRO_ENTRADA;
		ID = OLD.PRO_ID;

		LOCK TABLE "produtos";
		IF ANTIGO != NOVO THEN
			INSERT INTO HISTORICO (HIS_DATA,HIS_VALOR_ANTIGO, HIS_VALOR_ATUALIZADO,FK_PRODUTO) VALUES (CURRENT_DATE,ANTIGO,NOVO,ID);
		ELSE
			
		END IF;

		RETURN NEW;
	END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER TR_HISTORICO AFTER UPDATE OF PRO_ENTRADA ON PRODUTOS FOR EACH ROW EXECUTE PROCEDURE HISTORICO();

DROP TRIGGER TR_HISTORICO ON PRODUTOS;
DROP FUNCTION HISTORICO();