CREATE SEQUENCE sequencia INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;

ALTER TABLE historico ALTER COLUMN his_id SET DEFAULT NEXTVAL('sequencia'::regclass);

CREATE FUNCTION HISTORICO() RETURNS TRIGGER AS $$
DECLARE
	 ANTIGO NUMERIC (9,2);
	 NOVO NUMERIC (9,2);
	 ID INT;
BEGIN
	ANTIGO = OLD.PRO_ENTRADA;
	NOVO = NEW.PRO_ENTRADA;
	ID = OLD.PRO_ID;

	LOCK TABLE "produtos";
	INSERT INTO HISTORICO (HIS_DATA,HIS_VALOR_ANTIGO, HIS_VALOR_ATUALIZADO,FK_PRODUTO) VALUES (CURRENT_DATE,ANTIGO,NOVO,ID);

	RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER TR_HISTORICO AFTER UPDATE OF PRO_ENTRADA ON PRODUTOS FOR EACH ROW EXECUTE PROCEDURE HISTORICO();

DROP TRIGGER TR_HISTORICO ON PRODUTOS;
DROP FUNCTION HISTORICO();