/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.siroc.interfaces;

import br.com.siroc.Editor.Editor;
import br.com.siroc.dao.DAO;
import br.com.siroc.modelo.Fornecedor;
import br.com.siroc.modelo.Produto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matt
 */
public class ListagemProdutos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Listagem_Produtos
     */
    List<Fornecedor> fornecedores;
    List<Produto> produtos;
    DAO<Produto> pdao = new DAO<Produto>(Produto.class);
    DAO<Fornecedor> fdao = new DAO<Fornecedor>(Fornecedor.class);
    //definição das colunas da tabela
    DefaultTableModel tmProduto = new DefaultTableModel(null, new String[]{"Nome", "Peso", "Fornecedor", "Valor Entrada", "Valor Saída"}) {
        boolean[] canEdit = new boolean[]{
            false, false, false, false, false, false
        };

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit[columnIndex];
        }
    };

    JDesktopPane painel;

    public ListagemProdutos(JDesktopPane painel) {
        super("Cella - Listagem de Produtos");
        initComponents();
        tabela.setRowHeight(23);
        this.painel = painel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLCabecalho = new javax.swing.JLabel();
        jBLimpar = new javax.swing.JButton();
        jTNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jTFornecedor = new javax.swing.JTextField();
        jLNome_Produto = new javax.swing.JLabel();
        jLNome_Produto1 = new javax.swing.JLabel();

        setClosable(true);

        jLCabecalho.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLCabecalho.setText("Pesquisa de Produtos");

        jBLimpar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/siroc/Imagens/limpar.png"))); // NOI18N
        jBLimpar.setText("Limpar");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });

        jTNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNomeKeyTyped(evt);
            }
        });

        tabela.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabela.setModel(tmProduto);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jTFornecedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFornecedorKeyTyped(evt);
            }
        });

        jLNome_Produto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLNome_Produto.setText("Nome Produto:");

        jLNome_Produto1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLNome_Produto1.setText("Nome Fornecedor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBLimpar)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCabecalho)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLNome_Produto)
                            .addGap(18, 18, 18)
                            .addComponent(jTNome))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLNome_Produto1)
                            .addGap(18, 18, 18)
                            .addComponent(jTFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLCabecalho)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNome_Produto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNome_Produto1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBLimpar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jBLimparActionPerformed



    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        if (tabela.getSelectedRowCount() < 1) {
            JOptionPane.showMessageDialog(ListagemProdutos.this, "Favor, escolher um Produto!", "ERROR 404 - Product not found!", JOptionPane.ERROR_MESSAGE);
        } else {

        }
    }//GEN-LAST:event_jBAlterarActionPerformed


    private void jTNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNomeKeyTyped
        jTFornecedor.setText("");

        while (tmProduto.getRowCount() > 0) {
            tmProduto.removeRow(0);
        }

        produtos = pdao.buscaPorNome(jTNome.getText());
        for (int i = 0; i < produtos.size(); i++) {
            tmProduto.addRow(new String[]{null, null, null, null});
            tmProduto.setValueAt(produtos.get(i).getNome(), i, 0);
            tmProduto.setValueAt(produtos.get(i).getPeso() + " kg", i, 1);
            tmProduto.setValueAt(produtos.get(i).getFornecedor().getNome(), i, 2);
            tmProduto.setValueAt(Editor.format(produtos.get(i).getValor_entrada()), i, 3);
            tmProduto.setValueAt(Editor.format(produtos.get(i).getValor_saida()), i, 4);
        }
    }//GEN-LAST:event_jTNomeKeyTyped

    private void jTFornecedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFornecedorKeyTyped
        jTNome.setText("");
        while (tmProduto.getRowCount() > 0) {
            tmProduto.removeRow(0);
        }

        fornecedores = fdao.buscaPorNome(jTFornecedor.getText());

        produtos = new ArrayList<Produto>();

        for (int i = 0; i < fornecedores.size(); i++) {
            for (int j = 0; j < fornecedores.get(i).getProdutos().size(); j++) {
                produtos.add(fornecedores.get(i).getProdutos().get(j));
            }
        }

        for (int i = 0; i < produtos.size(); i++) {
            tmProduto.addRow(new String[]{null, null, null, null});
            tmProduto.setValueAt(produtos.get(i).getNome(), i, 0);
            tmProduto.setValueAt(produtos.get(i).getPeso() + " kg", i, 1);
            tmProduto.setValueAt(produtos.get(i).getFornecedor().getNome(), i, 2);
            tmProduto.setValueAt(Editor.format(produtos.get(i).getValor_entrada()), i, 3);
            tmProduto.setValueAt(Editor.format(produtos.get(i).getValor_saida()), i, 4);

        }    }//GEN-LAST:event_jTFornecedorKeyTyped

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        if (evt.getButton() != evt.BUTTON3 && evt.getClickCount() == 2) {
            AtualizaProduto ap = new AtualizaProduto(produtos.get(tabela.getSelectedRow()));
            ap.setVisible(true);
        }
    }//GEN-LAST:event_tabelaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBLimpar;
    private javax.swing.JLabel jLCabecalho;
    private javax.swing.JLabel jLNome_Produto;
    private javax.swing.JLabel jLNome_Produto1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFornecedor;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables

    private void limpar() {
        ListagemProdutos lp = new ListagemProdutos(painel);
        painel.add(lp);
        lp.setVisible(true);
        this.dispose();
    }
}
